### ISSUE TITLE
generated url is not working

### ISSUE THREAD

**Issue by Ankit2357** [Courtsite/gcp-monitoring-to-teams#2]
I have followed the whole process as mentioned and  the generated URL is not even pinging to the teams channel.
Also, I saw that the procedure says that is for "static webhook", not sure it might br true or not but just pointing it out as I did not see the same title in the GCP console while putting the URL in gcp notification channel

**Comment by MrSaints** [comment]
We still use this, and it's been working for us.

A few things to try...

1. Allowing all traffic

![2022-09-16-114220_543x278_scrot](https://user-images.githubusercontent.com/68859/190621623-61d9df71-275d-44e5-a359-5ee72ab350b5.png)

![2022-09-16-114142_480x331_scrot](https://user-images.githubusercontent.com/68859/190621618-cd1ab3aa-eaae-457b-9d3d-de16798fb555.png)

2. Check the logs

![2022-09-16-114336_449x174_scrot](https://user-images.githubusercontent.com/68859/190621841-7a49bf17-bfbf-41aa-86a9-1306c14cd738.png)
![2022-09-16-114344_851x50_scrot](https://user-images.githubusercontent.com/68859/190621843-4f2933bc-1edb-43a7-8d22-c629817f88be.png)

Do you see anything at all?

> not sure it might br true or not but just pointing it out as I did not see the same title in the GCP console while putting the URL in gcp notification channel

Yeah, they've since updated the UI.

If you added it under `Notification channels`, you're on the right track.

Example:

![2022-09-16-114452_335x396_scrot](https://user-images.githubusercontent.com/68859/190622072-a0bb60b5-325e-4de3-9198-f3564a0e8cbc.png)

Click on "Test connection" if you haven't already.

**Comment by idlukakas** [comment]
I just found from stackoverflow and it works for me:

"It seems to me that additional IAM functionality was added to Google Cloud Functions, and as a result, you may have not turned on allUser access to the function (FYI this give acess to the whole web).

On the Cloud Functions homepage, highlight the Cloud Function you want to add all access to.

Click "Permissions" on the top bar.

Click "Add Principal" and type "allUsers" then select "Cloud Function Invokers" under "Cloud Function" in the Role box.

Click "Save"

Click "Allow Public Access"
"
Source: https://stackoverflow.com/questions/52539441/403-response-from-google-cloud-functions
